# Generated by Django 5.0.6 on 2024-06-30 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_base', '0003_article_personid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to='api_base.person')),
                ('Departement', models.CharField(max_length=40)),
                ('Fonction', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JournalID', models.CharField(max_length=40)),
                ('Name', models.CharField(max_length=40)),
                ('Link', models.CharField(max_length=40)),
                ('Image', models.CharField(max_length=400)),
            ],
        ),
    ]
