# Generated by Django 5.0.6 on 2024-07-01 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_base', '0004_admin_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='editeur', serialize=False, to='api_base.person')),
                ('Thematique', models.CharField(max_length=40)),
            ],
        ),
    ]
