# Generated by Django 5.0.6 on 2024-07-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_base', '0005_editeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Status',
            field=models.CharField(default='NApproved', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='Ref',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
