# Generated by Django 5.0.6 on 2024-07-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_base', '0006_article_status_alter_article_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EmmetteurID', models.CharField(max_length=40)),
                ('RecepteurID', models.CharField(max_length=40)),
                ('Conversation', models.CharField(max_length=40)),
                ('Contenu', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('EmmetteurID', models.CharField(max_length=40)),
                ('RecepteurID', models.CharField(max_length=40)),
                ('Conversation', models.CharField(max_length=40)),
                ('Contenu', models.CharField(max_length=400)),
            ],
        ),
    ]
