# Generated by Django 5.0.6 on 2024-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_base', '0007_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='Conversation',
            new_name='CreateurID',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='EmmetteurID',
            new_name='Logo',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='Contenu',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='RecepteurID',
        ),
        migrations.AddField(
            model_name='message',
            name='Time',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
